### ISSUE TITLE
Pressing the Enter key while working on the quiz

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#56] opened 2020-03-04 14:29 UTC
> **Migrated from Trello**

When the user clicks on a quiz element, the browser is focused on the form and the form is submitted when the user presses the Enter key on the keyboard. This tends to cause accidental submissions since users seem to more often hit Enter unintentionally than intentionally. What could be done about this?

**Comment by Mankro** [comment] 2020-06-17 09:22
@mtthwhggns do you think it would be OK to simply disable form submissions with the Enter key? I suppose people who can't use the mouse would then not be able to submit, so that is not the right way to solve this issue. How could we avoid accidental submissions with the Enter key while also supporting users who only use the keyboard?

**Comment by mtthwhggns** [comment] 2020-06-17 10:04
Good question.

Enter submitting the form you're focused on is generally the expected behaviour, so I'd be reluctant to eliminate it completely, but it would still work if you activate the submit button using the keyboard. It's not terrible, but I'd still prefer it be the last resort.

The examples given are on a different topic, but I'd take a look at [WCAG SC 3.3.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-reversible.html) - it's about legal or financial information, but I think we could apply similar principles since the submissions are "consumed" and are finite. 

One way to achieve this is an intermediate screen (as in [G98](https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G98)), where after submitting a questionnaire (I don't think we have the same problem with file upload exercises), the fields get `disabled=true` and a second panel appears asking the user to "confirm" their submission. We could exen train keyboard focus on the "change answers"-type button. 

I mocked this up in a few minutes, nothing works yet:

![Confirmation example](https://user-images.githubusercontent.com/6674046/84884814-ddbfad00-b09a-11ea-941f-fa03359e72ee.png)

This could all be achieved with a relatively small amount of Javascript.

**Comment by raphendyr** [comment] 2020-06-17 11:33
I like the @mtthwhggns's mockup.

**Comment by Mankro** [comment] 2020-06-18 14:31
Yeah, it is a good idea.

**Comment by raphendyr** [comment] 2020-07-15 13:02
Note, this should be fixed in A+. Hence, please continue the conversation in https://github.com/apluslms/a-plus/issues/508 

Nevertheless, a marker is required so A+ can know that it's ok to edit the DOM (e.g. `class="aplus-submit"`).

I close this in favour of conversation in the correct repo.

**Closed by raphendyr** 2020-07-15 13:02 UTC
Labels: area: UX student, effort: hours, experience: good first issue, priority: low, type: feature
