### ISSUE TITLE
Support (much) faster Scala compilations

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/mooc-grader#68] opened 2020-04-16 13:16 UTC
>**Migrated from Trello**

At least as "fast" as we used to have before containerization. (Currently, even the most trivial Scala program takes dozens of seconds or even more than a minute to compile.)

**Comment by jsorva** [comment] 2023-01-29 13:39
This is essentially a duplicate of this issue in the MOOC Grader repo, which I suppose is the correct place for this: https://github.com/apluslms/mooc-grader/issues/141

**Closed** 2023-03-22 18:59 UTC
Labels: type: feature, O1 needs, priority: high, area: performance, status: requires a priority
